[tool.poetry]
name = "pyntrinio"
version = "0.1.18"
description = "Python package that draws needed data from intrinio API objects."
authors = ["Roc Zhang <roc_zhang@hotmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/UBC-MDS/pyntrinio/"
repository = "https://github.com/UBC-MDS/pyntrinio/"
documentation = 'https://pyntrinio.readthedocs.io'

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.1"
intrinio_sdk = "^5.1.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.8.1"
pytest = "^5.3.5"
codecov = "^2.0.16"
flake8 = "^3.7.9"
sphinx = "^2.4.4"
sphinxcontrib-napoleon = "^0.7"
python-semantic-release = "^4.10.0"

[tool.semantic_release]
version_variable = "pyntrinio/__init__.py:__version__"
version_source = "commit"
upload_to_pypi = "false"
patch_without_tag = "true"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"